# Generated by Django 4.2.2 on 2025-01-20 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_dates_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 20, 12, 24, 11, 172582, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
