# Generated by Django 4.2.2 on 2025-01-20 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 20, 17, 28, 33, 379764, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
